### ISSUE TITLE
CSS file not in the correct place

### ISSUE THREAD

**Issue by mediaguycouk** [Panopto/Blackboard-9.1-Plugin-for-Panopto#1]
main.css needs to also be in the /css/main.css folder to work on April 2014 and later.

**Comment by Panopto** [comment]
Thank you for the heads up! I filed it in our internal bug tracking system and we will be sure to move it over in an upcoming release.

Bug 27565:Blackboard CSS file needs to move to /css/main.css

**Comment by jmalmsten-panopto** [comment]
Ok, 

It's been a while but I handled this, main.css is now located in the css folder.

Thank you for your patience!

Joe M.
